### ISSUE TITLE
FE: [refactor] invitation dialog

### ISSUE THREAD

**Issue by cch5ng** [hatchways/team-penguin#54]
- [ ] (moved to #52) use dynamic auth user state to get logged in email
- [ ] (moved to #52) define a default route on the authenticated app component (when login succeeds, it should redirect there)
- [ ] (fixed in #65) look at the invitation dialog bug (probably place condition on the request for referralId, like only request if dialog state is open)
- [x] (low) use material ui validation component/styling for input errors
- [x] (low) somehow display error message when the invitation send button is clicked and an error results (json returns the error but nothing is done with it now); try to be consistent with the login component
- [x] (low) try to fix the positioning of the copy button; right now the css position is pretty brittle so if time, try to save btn as svg and use custom icon, placed within input for more consistent placement
